# Build stage
FROM node:19-alpine

WORKDIR /app/server

COPY ./server/package*.json ./

COPY ./server .

RUN npm install  && npm cache clean --force

RUN npm install -g nodemon

EXPOSE 5001 5433 9229

CMD ["npm", "run", "server"]