services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile-ui
    volumes:
      - ./ui/src:/app/ui/src
    ports:
      - ${VITE_PROJECT_PORT}:${VITE_PROJECT_PORT}
    env_file:
      - .env
    networks:
      - crunchi-network
  pgdb:
    image: postgres
    ports:
      - ${POSTGRES_PORT_MAP}:${POSTGRES_PORT}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - crunchi-network
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    volumes:
      - ./server:/app/server
      - ./server/uploads/img:/app/server/uploads/img
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - "9229:9229"
    env_file:
      - .env
    depends_on:
      - pgdb
    networks:
      - crunchi-network
    # command: yarn nodemon -L --inspect=0.0.0.0:9229 --signal SIGINT --nolazy server.js
networks:
  crunchi-network:
    external: true

  