version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-chat
    volumes:
      - ./src:/app/src
    ports:
      - ${VITE_PROJECT_PORT}:${VITE_PROJECT_PORT}
    env_file:
      - .env


  