# syntax=docker/dockerfile:1

FROM node:19-alpine

WORKDIR /app/ui

COPY ./ui/package*.json ./

RUN npm install  && npm cache clean --force

COPY ./ui ./

EXPOSE 5005 5433 3010 5002 5010

CMD ["npm", "run", "dev"]