services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile-ui
    volumes:
      - ./ui/src:/app/ui/src
    ports:
      - ${VITE_PROJECT_PORT}:${VITE_PROJECT_PORT}
    env_file:
      - .env
    networks:
      - code-network
  pgdb:
    image: postgres
    ports:
      - ${POSTGRES_PORT_MAP}:${POSTGRES_PORT}
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - code-network
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    volumes:
      - ./server:/app/server
      - ./server/uploads/img:/app/server/uploads/img
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    depends_on:
      - pgdb
    networks:
      - code-network
  db-prompt:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: ${PROMPT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PROMPT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PROMPT_POSTGRES_DB}
    ports:
      - ${PROMPT_POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - code-network
  prompt-service:
    build:
      context: ./services/spring-boot-prompt-service
      dockerfile: Dockerfile-prompt
    ports:
      - ${PROMPT_SERVICE_PORT}:${PROMPT_SERVICE_PORT}
    environment:
      SPRING_CONFIG_LOCATION: file:/config/application.properties
    volumes:
      - ./config:/config
    depends_on:
      - db-prompt
    networks:
      - code-network
networks:
  code-network:
    external: true
