# syntax=docker/dockerfile:1

FROM node:19-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install  && npm cache clean --force

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY ./ ./

EXPOSE 5005 5433 3005 5002 5010

CMD ["npm", "run", "dev"]