version: '3'
services:
  chat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./upload/img:/app/upload/img
    ports:
      - 5001:5001
    env_file:
      - .env
    depends_on:
      - pgdb
    networks:
      - chat-network
  pgdb:
    image: postgres
    ports:
      - 5433:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - chat-network
networks:
  chat-network:
    external: true
  